<<: !include
  file: channel.yaml
  vars:
    channel_id: ${channel_5_id}
    channel_sensor_id: ${channel_5_sensor_id}
    entity_id: ${channel_5_entity_id}
    entity_name: ${channel_5_entity_name}