<<: !include
  file: channel.yaml
  vars:
    channel_id: ${channel_4_id}
    channel_sensor_id: ${channel_4_sensor_id}
    entity_id: ${channel_4_entity_id}
    entity_name: ${channel_4_entity_name}