!include
  file: channel.yaml
  vars:
    channel_id: ${channel_16_id}
    channel_sensor_id: ${channel_16_sensor_id}
    entity_id: ${channel_16_entity_id}
    entity_name: ${channel_16_entity_name}