<< !include
  file: channel.yaml
  vars:
    channel_id: ${channel_15_id}
    channel_sensor_id: ${channel_15_sensor_id}
    entity_id: ${channel_15_entity_id}
    entity_name: ${channel_15_entity_name}