<<: !include
  file: channel.yaml
  vars:
    channel_id: ${channel_3_id}
    channel_sensor_id: ${channel_3_sensor_id}
    entity_id: ${channel_3_entity_id}

    entity_name: ${channel_3_entity_name}
    device_id: ${channel_3_device_id}
