!include
  file: channel.yaml
  vars:
    channel_id: ${channel_6_id}
    channel_sensor_id: ${channel_6_sensor_id}
    entity_id: ${channel_6_entity_id}
    entity_name: ${channel_6_entity_name}