!include
  file: channel.yaml
  vars:
    channel_id: ${channel_9_id}
    channel_sensor_id: ${channel_9_sensor_id}
    entity_id: ${channel_9_entity_id}
    entity_name: ${channel_9_entity_name}