<<: !include
  file: channel.yaml
  vars:
    channel_id: ${channel_8_id}
    channel_sensor_id: ${channel_8_sensor_id}
    entity_id: ${channel_8_entity_id}

    entity_name: ${channel_8_entity_name}
    entity_device_id: ${channel_8_device_id}

